name: control

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./src

jobs:
  build:
    name: build
    
    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET standard 2.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.x
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
      
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore
      
